name: my_profile_microfrontend
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  common_microfrontend:
    path: ../common_microfrontend

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  faker: ^2.2.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7


flutter:
