name: common_microfrontend
description: "A new Flutter package project."
version: 1.0.0
publish_to: "none"
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  equatable: ^2.0.5
  modular_core: 3.3.2
  flutter_bloc: ^8.1.6
  flutter_modular: 6.3.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  intl: 0.19.0
  intl_phone_number_input: ^0.7.4
  bloc: ^8.1.4
  google_fonts: ^6.2.1
  flutter_font_icons: ^2.2.7
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  extended_masked_text: ^3.0.1
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.0+1
  app_settings: ^5.1.1
  network_info_plus: ^6.1.0
  carousel_slider_plus: ^7.0.1
  # html: ^0.15.4
  # flutter_widget_from_html: ^0.15.2
  share_plus: ^10.1.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

  open_settings_plus: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  faker: ^2.1.0
  husky: ^0.1.7
  bloc_test: ^9.1.7

flutter:
  assets:
    - assets/icons/