name: appcore
description: "A new Flutter package project."
version: 1.0.0
publish_to: "none"


environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  common_microfrontend:
      path: ../common_microfrontend

  settings_microfrontend:
      path: ../settings_microfrontend

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

